### ISSUE TITLE
Better user documentation

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#107]
In discussion with @AgnesBelt, it would be good to document the key basic concepts for a new user describing a standard workflow. This could be through a GIF or video embedded in the documentation.

There are three key commands:
1. generate excel file
  – how to use Excel as an interface with a better workflow structure
    – understand how the file is structured 
    – define sets e.g. emissions and technologies first
1. generate input datafile
2. convert the results

**Comment by trevorb1** [comment]
Documentation updates to address these points have been implemented in PR #137 (https://otoole.readthedocs.io/en/latest/index.html)! 

Specifically, examples have been added to show how to generate a template excel file for data input, a data formats page has been added to explain the different supported file formats, and examples have been added elaborating on the data conversion and result processing process 🙂
