### ISSUE TITLE
CapitalInvestment

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/otoole#117]
The latest updates of the OSeMOSYS code introduce the `CapitalRecoveryFactor` and the `PvAnnuity`.
In the calculation of the `CapitalInvestment` in otoole this is not yet considered.

**Comment by willu47** [comment]
These are internally calculated parameters and are used only for the calculation of financials. Otoole already computes these using [capital_recovery_factor](https://github.com/OSeMOSYS/otoole/blob/77606e9966fc8bce0bd7471049d0051f3ca9aff3/src/otoole/results/result_package.py#L758)
