### ISSUE TITLE
Converting from Data File to Excel File 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/otoole#127]
When converting from a data file to an excel file, the conversion completes but the file is 0KB in size and Excel gives me this error when I try to open it. 

![image](https://user-images.githubusercontent.com/67297083/203679340-90430742-fc56-44bb-b6f9-722d3cc24074.png)

**OS**: Linux
**Branch**: Develop 
**Command**: `otoole convert datafile excel data.txt data.xlsx config.yaml `
**Data Format**: otoole and momani

**Log**: 
Just a sample below, but its the same for most/all parameters and sets, regardless if the parameter/set has data or not. 

```
INFO:root:Checking datatypes for AccumulatedAnnualDemand
INFO:root:dtype of column REGION does not match str for parameter AccumulatedAnnualDemand
INFO:root:dtype of column FUEL does not match str for parameter AccumulatedAnnualDemand
INFO:root:dtype of column YEAR does not match int for parameter AccumulatedAnnualDemand
INFO:root:Checking datatypes for AnnualEmissionLimit
INFO:root:dtype of column REGION does not match str for parameter AnnualEmissionLimit
INFO:root:dtype of column EMISSION does not match str for parameter AnnualEmissionLimit
INFO:root:dtype of column YEAR does not match int for parameter AnnualEmissionLimit
INFO:root:Checking datatypes for AnnualExogenousEmission
INFO:root:dtype of column REGION does not match str for parameter AnnualExogenousEmission
INFO:root:dtype of column EMISSION does not match str for parameter AnnualExogenousEmission
INFO:root:dtype of column YEAR does not match int for parameter AnnualExogenousEmission
```

**Other Info**
I did a test of using the same `data.txt` and `config.yaml` file to just convert to another data file (ie. `otoole convert datafile datafile`) and that worked fine. So I would guess the error is somewhere in the writing data process, rather then the reading data process.

**Comment by willu47** [comment]
I have managed to replicate this error.  The cause is the length of the parameter names exceed the maximum allowed by excel - 31 characters - as the name of a tab.

```python
miniconda3/envs/otoole38/lib/python3.9/site-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
```

The current solution is to store long OSeMOSYS parameter names in a dictionary (in `src/otoole/read_strategies.py`) and switch them out for a abbreviated version.  This worked when we had a guarantee of the parameter name, but will need to be changed for v1.0 in which we allow any GNU MathProg model.

**Comment by willu47** [comment]
Superseded by #128
