### ISSUE TITLE
Add deprecation errors to Read/WriteDataPackage methods

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#135]
For v1.0, I suggest that we deprecate (remove) all code associated with reading and writing datapackages and the dependencies on frictionless data.  It would be nice to include this in the future, but it does not really add anything to the ReadCsv and WriteCsv classes.

We should add deprecation errors to the main branch and make a release to warn current users of the pending change.

We can retain the class methods, raise a warning and forward the request to ReadCsv or WriteCsv (amending the path argument).

**Comment by trevorb1** [comment]
Closed with PR #141
