### ISSUE TITLE
[Bug]: `ProductionByTechnologyAnnual` result not being written 

### ISSUE THREAD

**Issue by vignesh1987** [OSeMOSYS/otoole#201]
### The Issue

When I am writing results using Otoole's results writing command, the results for "**ProductionByTechnologyAnnual**" are not printed ( as a csv). I checked my config.yaml file and [result_package.py]. Both have the results variable correctly declared.(https://github.com/OSeMOSYS/otoole/blob/master/src/otoole/results/result_package.py). Is there any other place I must be looking to get "ProductionByTechnologyAnnual" as part of the regular results set? 
Also, to say that "**ProductionByTechnology**" is getting printed correctly. 

### Operating System

Windows

### What version of otoole are you running?

1.1.0

**Comment by trevorb1** [comment]
Hi @vignesh1987; thanks for reporting the issue! 

Unfortunately, I wasn't able to recreate the issue on my side. I ran [`Simplicity`](https://github.com/OSeMOSYS/simplicity) with `osemosys_fast`, solved with `cbc`, and used `otoole`'s `result` function to produce a folder of result CSVs; in this folder I have a `ProductionByTechnologyAnnual.csv` file. Are you able to please print out logging statement when you run otoole via the `-v` flag (ie. `otoole -v results ...` or `otoole -vvv results ...`) and paste them here to try and isolate the issue. Thanks!

**Comment by vignesh1987** [comment]
Hi Trevor,
Thanks for checking. It was my mistake. I hashed out the ProductionByTechnologyAnnual constraint in the code by mistake and failed to turn it on.
Thanks
Vignesh
