### ISSUE TITLE
[DOCS]: Incorrect syntax in the Python API page for Reading results

### ISSUE THREAD

**Issue by vignesh1987** [OSeMOSYS/otoole#231]
### Type of documentation issue.

Incorect Information

### Issue Description

On the Python API page, the section on reading result files has a syntax error. It read as follows
`from otoole import read_results` 
`read_results('my_model.yaml', 'cbc', 'csv', 'my_model.sol', 'my_model_csvs', 'datafile', 'my_model.dat')` 

However, it should be as follows. The syntax does not need the CSV definition, as we are just creating a Tuple from the results. 
`from otoole import read_results` 
`read_results('my_model.yaml', 'cbc', 'my_model.sol', 'datafile', 'my_model.dat')` 

The syntax in the module reference page of [otoole.convert.read_results()](https://otoole.readthedocs.io/en/latest/api/otoole.html#otoole.convert.read_results) is correct

### Link to existing documentation

https://otoole.readthedocs.io/en/latest/convert.html

### Suggested Update

The syntax should be 
`read_results('my_model.yaml', 'cbc', 'my_model.sol', 'datafile', 'my_model.dat')`

**Comment by trevorb1** [comment]
Thanks for reporting and including the clear solution, @vignesh1987! Should be fixed now :)
