### ISSUE TITLE
Error running Simplicity

### ISSUE THREAD

**Issue by fkanyako** [OSeMOSYS/otoole#26]
Hi,
I am trying to run simplicity to create a GNU MathProg datafile input file.
Unfortunately, am running into this error:

C:\Desktop\OSEMOSYS>otoole convert datapackage datafile https://zenodo.org/record/3479823/files/OSeMOSYS/simplicity-v0.1a0.zip ./simplicity.txt

usage: otoole [-h] [--verbose] [--version] {prep,convert,cplex,viz} ...
**otoole: error: unrecognized arguments:** datapackage datafile https://zenodo.org/record/3479823/files/OSeMOSYS/simplicity-v0.1a0.zip ./simplicity.txt

What am I doing wrong? and also how can I use this code with my open data stored on my laptop?

Thank you
Franklyn

**Comment by willu47** [comment]
To answer your longer question, the idea behind *otoole* and the simplicity Tabular Data Package is that this provides a more structured and interoperable way of working with OSeMOSYS. The [simplicity](OSeMOSYS/simplicity) data package is an example of that formal structure - a folder of comma-separate value (CSV) files together with a JSON metadata file which describes the structure of the data.  

The *otoole* package than allows us to convert between data formats - from an OSeMOSYS data file (in AMPL text format) to Tabular Data Package and back again.

At present, to use *otoole*, you would need to present your data in one of the formats that it supports. The easiest way may be to look at the simplicity example which you can download from [here](https://github.com/OSeMOSYS/simplicity/archive/v0.1a0.zip)

**Comment by fkanyako** [comment]
Thank you

**Comment by LuiscarlosTorres** [comment]
Hello,

I installed Otoole using the Anaconda prompt, as suggested in the repository.

I am trying to convert csv into datafile (from Simplicity). I do it by first activating "myenv" in Anaconda, then call Otoole the following way:
------------------------------------------------------
otoole convert csv datafile <frompath> <topath>
------------------------------------------------------

But the conversion cannot be carried out. The following message pops up:

-------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\lats1\anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lats1\anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LATS1\Anaconda3\envs\myenv\Scripts\otoole.exe\__main__.py", line 7, in <module>
  File "c:\users\lats1\anaconda3\envs\myenv\lib\site-packages\otoole\cli.py", line 191, in main
    args.func(args)
  File "c:\users\lats1\anaconda3\envs\myenv\lib\site-packages\otoole\cli.py", line 111, in conversion_matrix
    raise NotImplementedError(msg)
NotImplementedError: Conversion from csv to datafile is not yet implemented

------------------------------------------------------------------------------------------

Can you please help me?

Thank you, 

Luiscarlos
