### ISSUE TITLE
CPLEX results processing only produces three outputs

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#28]
Running `otoole cplex solutionCPLEX.txt  test.csv csv` only produces results for three result parameters: `NewCapacity`, `TotalCapacityAnnual` and `RateofActivity`.

**Comment by vignesh1987** [comment]
This could be because (my first guess) in the JRC project, we wanted to cut the optimization/solving time. Hence, we wrote the calculation of other result variables outside (in the python).  Probably, the results are being printed out later in the pipeline. Is that the case?

**Comment by willu47** [comment]
Closed by 8650647a18bffaa5f632593bc708bbf2802d164a
