### ISSUE TITLE
Refactor visualisation code to use dict of pandas dataframes

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#50]
Currently, the reference energy system code expects a datapackage. It should be generalised to use the dict of pandas dataframes now used as the internal data store in otoole. This would allow easier generation of diagrams from formats other than datapackage (e.g. from datafiles).

**Comment by trevorb1** [comment]
With the release of version 1.0.0, the `viz res` command now takes in the internal datastore structure `Dict[str, pd.DataFrame]`, allowing `viz res` to be called with any of `datafile`, `csv`, `excel` formats

https://github.com/OSeMOSYS/otoole/blob/0240350c971ddc5981f9e1c56f3175c3fa86d53f/src/otoole/visualise/res.py#L199-L211
