### ISSUE TITLE
Too long parameter names for excel sheets

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/otoole#51]
The conversion from datapackage to exel works. However, the conversion back throws a bug since parameter with more than 31 letters are cut down to 31 by excel, since worksheet names can't be longer than that. Due to that the parameter name is then not correct anymore and the script doesn't find it.

**Comment by HauHe** [comment]
Applies for:
TotalAnnualMaxCapacityInvestment
TotalAnnualMinCapacityInvestment
TotalTechnologyAnnualActivityLowerLimit
TotalTechnologyAnnualActivityUpperLimit
TotalTechnologyModelPeriodActivityUpperLimit

**Comment by willu47** [comment]
Thanks @HauHe - this should work as there is a function which performs this conversion.

I'll follow this up and have a look.

```python
def _modify_names(sheet_names: List) -> List:
    """I change the name of the sheets in the xlsx file to match with the csv
    actual ones
    """
    modifiedNames = sheet_names.copy()
    for name in modifiedNames:
        if name == "TotalAnnualMaxCapacityInvestmen":
            name = "TotalAnnualMaxCapacityInvestment"
        elif name == "TotalAnnualMinCapacityInvestmen":
            name = "TotalAnnualMinCapacityInvestment"
        elif name == "TotalTechnologyAnnualActivityLo":
            name = "TotalTechnologyAnnualActivityLowerLimit"
        elif name == "TotalTechnologyAnnualActivityUp":
            name = "TotalTechnologyAnnualActivityUpperLimit"
        elif name == "TotalTechnologyModelPeriodActLo":
            name = "TotalTechnologyModelPeriodActivityLowerLimit"
        elif name == "TotalTechnologyModelPeriodActUp":
            name = "TotalTechnologyModelPeriodActivityUpperLimit"
    return modifiedNames
```

**Comment by willu47** [comment]
Okay, found the issue.  When converting from datapackage to Excel, we need to actively rename those names over 31 characters so they don't get truncated and are subsequently unidentifiable. For example, `TotalTechnologyModelPeriodActiv` could be either the upper or lower limit...
