### ISSUE TITLE
Link to read the docs

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/otoole#59]
Perhaps I'm missing it, then please ignore the issue, but to me it seems there is no link to the related read the docs in the repository.

**Comment by willu47** [comment]
Good point. The only link is from the "docs - passing" badge at the top of the readme. Do you want to make a pull request with the link added in the readme text together with a description of how to get help?

**Comment by HauHe** [comment]
Sure, I will try.

**Comment by HauHe** [comment]
What do you refer to with how to get help? The OSeMOSYS forum?
