### ISSUE TITLE
Unable to implement ReadMemory routine in otoole.input module from documentation example

### ISSUE THREAD

**Issue by wogandavid** [OSeMOSYS/otoole#67]
I have a Python dictionary where the keys are OSeMOSYS parameter names and the keys are dataframes of sets and values. I am following the example in the [otoole.input submodule reference page](https://otoole.readthedocs.io/en/stable/api/otoole.html#subpackages) to test reading this dataframe from memory and converting to another data format.

I import otoole using `import otoole` and try to define the read and write instructions:

```
reader = ReadMemory(parameters)
writer = WriteExcel()
converter = Context(read_strategy=reader, write_strategy=writer)
converter.convert('.', 'osemosys_to_excel.xlsx')
```

I understand the process to be: define the read and write strategies as `ReadMemory` and `WriteExcel`, respectively. Then pass those to a context, and finally declare the file paths for the converter. `parameters` is the dictionary containing the OSeMOSYS parameter names and dataframes.

However, `ReadMemory` and `WriteExcel` are unknown, producing a NameError `(name 'ReadMemory' is not defined)`. Looking at the documentation, I can see that `ReadMemory` and `WriteExcel` exist, but I am unable to access them. Perhaps I am misunderstanding some concepts in Python about accessing attributes or working with classes. In any case, I am unsure if the functionality does not exist or if more instructions in the example would be helpful.

I also experimented with specifically importing input `from otoole import input` and trying access via attributes but without success.

I am using an environment with Python 3.7 and otoole 0.8.2.

**Comment by willu47** [comment]
Hi @wogandavid - thanks for the question. I'll update the documentation to make the use of the read strategies a bit clearer.

You need to first import the Read- and Write-Strategies from `otoole.read_strategies` and `otoole.write_strategies`. A full example is:

```python
from otoole.read_strategies import ReadMemory
from otoole.write_strategies import WriteExcel
parameters = {} # Assign your OSeMOSYS parameter contents to the parameters variable here
reader = ReadMemory(parameters)
writer = WriteExcel()
converter = Context(read_strategy=reader, write_strategy=writer)
converter.convert('.', 'osemosys_to_excel.xlsx')
```

**Comment by wogandavid** [comment]
Hi @willu47 thanks for the clarification. I suspected I had forgotten something like that. One amendment to the example is importing Context:

```
from otoole.read_strategies import ReadMemory
from otoole.write_strategies import WriteExcel
from otoole.input import Context
parameters = {} # Assign your OSeMOSYS parameter contents to the parameters variable here
reader = ReadMemory(parameters)
writer = WriteExcel()
converter = Context(read_strategy=reader, write_strategy=writer)
converter.convert('.', 'osemosys_to_excel.xlsx')
```
