### ISSUE TITLE
Combine configuration for inputs and results into one file

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#76]
Configuration for an OSeMOSYS model should:
- combine inputs and outputs in one structured file
- point to the version of the OSeMOSYS model it is compatible with (allow user-defined configuration - see #56)
- be exportable

**Comment by trevorb1** [comment]
Hi @willu47. Is this one okay to be closed? I think the first 2 bullet points have now been addressed, but I just want to clarify what being exportable means. I think it just means that the configuration file is a separate file, and not hard coded into otooles file structure? If so we should be good to close this! Please let me know if I misinterpreted though and you meant something else. Thanks!
