### ISSUE TITLE
Installing otoole/pygraphviz

### ISSUE THREAD

**Issue by fkanyako** [OSeMOSYS/otoole#8]
I had lots of problems (Failed building wheel for pygraphviz) installing otoole because it requires this package: pygraphviz. Apparently installing pygraphviz on windows10 x64 is still a serious problem the community haven't addressed yet. 

If you have windows 10 x64  and anaconda installed, and ran into trouble from pygraphviz, here is a workaround:
1. First, install pygraphviz: "conda install -c alubbock pygraphviz"
(https://stackoverflow.com/questions/40809758/howto-install-pygraphviz-on-windows-10-64bit) The last reply worked for me. 

Once this works, go back to otoole: "pip install otoole" and you are good to go.

This is for anyone who might encounter this problem installing otoole on windows 10.

**Comment by willu47** [comment]
I added a work around in the [readme](https://github.com/OSeMOSYS/otoole#dependencies) which involves installing the dependencies using a conda environment.
