### ISSUE TITLE
Empty dataframe when converting results from cbc

### ISSUE THREAD

**Issue by milesjw** [OSeMOSYS/otoole#81]
Hi,

Similarly to #77, I am trying to convert a cbc solution file to a folder of csv files using otoole and osemosys_fast code:
`otoole convert csv datafile india_v0\data india_v5.txt`

Then generate the lp file:
`glpsol --check -m osemosys_fast.txt -d india_v5.txt --wlp cbcinput.lp`

And solve with CBC:
`cbc cbcinput.lp solve -solu cbcoutput.txt`

The model solves successfully and creates the lp file. However, when converting the results using 
`otoole results cbc csv cbcoutput.txt ./results --input_datafile india_v5.txt`
the following error appears:
![image](https://user-images.githubusercontent.com/51229317/95908532-d071b100-0d62-11eb-8532-12fd5cb6a62b.png)

When checking cbcoutput.txt, I realized that the only variables reported are NewCapacity and RateOfActivity. Might that be the source of the problem?

Data file: 
[india_v5.txt](https://github.com/OSeMOSYS/otoole/files/5373749/india_v5.txt)

Thanks in advance,
Miles

**Comment by willu47** [comment]
Hi @milesjw - thanks for the detailed issue. I was able to recreate each of the steps, but I cannot create the problem.  Which version of otoole are you using (`otoole --version`)?

**Comment by milesjw** [comment]
Thanks @willu47, that is strange. It's version 0.8.4

**Comment by willu47** [comment]
Agreed, it is a bit strange.  Okay, what about your Python, pandas and other versions?  If you're using conda, could you export your environment `conda env export > otoole_issue_81.yml` and upload it here?  Also, which version of cbc are you using?

**Comment by milesjw** [comment]
Python 3.8.3
CBC 2.10
How would you suggest to check the pandas version? Typing pandas in the cmd window in fact gives an error that the command is not recognized... maybe the problem lies in there?

I zipped the file because I can't upload a .yml, hope that works for you:
[otoole_issue_81.zip](https://github.com/OSeMOSYS/otoole/files/5380326/otoole_issue_81.zip)

**Comment by willu47** [comment]
Closing this as behaviour was expected - multiple result files are not being generated as the CBC solution file contains only two parameters.
