### ISSUE TITLE
Datatypes of modes of operation seem to be different

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#86]
[edited to clarify that issue is about mode of operation index datatype]
- Input activity ratio mode of operation index is a float
- Output activity ratio mode of operation index is an integer

**Comment by HauHe** [comment]
Do you want to say the OutputActivityRatio is always an integer?
I would disagree on that. In my models for example transmission has the InputActivityRatio of 1 but the OutputActivityRatio is a float e.g. 0.95.

**Comment by tniet** [comment]
Hi @willu47 @HauHe - I would agree with @HauHe, both IAR and OAR should be float.  Especially for CLEWs type analysis where OAR is used for rainfall and water balances it is definitely a float, but also in transmission situations as @HauHe states, co-generation and others.

**Comment by abhishek0208** [comment]
@HauHe @tniet the issue is related to the 'mode' column/index for Input and OutputActivityRatios, not the value itself.

**Comment by willu47** [comment]
@abhishek0208 - could you clarify what causes this? Is it from running `otoole convert` or something else?
